const { Schema, model } = require("mongoose");

const userSchema = new Schema(
  {
    email: {
      type: String,
      required: [true, "Oops! You forgot to enter your email."],
      unique: true,
      lowercase: true,
      trim: true,
    },
    password: {
      type: String,
      required: [true, "Hey there! Don't forget to set a password."],
    },
    username: {
      type: String,
      required: [true, "Uh-oh! You have to choose a username to get started."],
    },
    first_Name: {
      type: String,
      required: [true, "Hold on! We need your first name."],
    },
    surname: {
      type: String,
      required: [true, "Wait! your surname is missing."],
    },
    date_Of_Birth: {
      type: Date,
    },
    favourite_On_Nature: {
      type: String,
      enum: ["Animals", "Plants"],
    },
    favouriteSeason: {
      type: String,
      enum: ["Winter", "Spring", "Summer", "Autumn"],
    },
    profile_Image: {
      type: String,
      default:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGjt2yc1eucAzdqAa7ThZTYxtpMXXem3J16Q&usqp=CAU",
    },
    continent: {
      type: String,
      enum: ["Africa", "America", "Asia", "Europe", "Oceania"],
    },
    country: {
      type: String,
      validate: {
        validator: function (value) {
          // Check if the selected country is in the list corresponding to the chosen continent
          const validCountries = {
            Africa: [
              "Algeria",
              "Angola",
              "Benin",
              "Botswana",
              "Burkina Faso",
              "Burundi",
              "Cabo Verde",
              "Cameroon",
              "Central African Republic",
              "Chad",
              "Comoros",
              "Congo",
              "Côte d'Ivoire",
              "Djibouti",
              "Egypt",
              "Equatorial Guinea",
              "Eritrea",
              "Eswatini",
              "Ethiopia",
              "Gabon",
              "Gambia",
              "Ghana",
              "Guinea",
              "Guinea-Bissau",
              "Kenya",
              "Lesotho",
              "Liberia",
              "Libya",
              "Madagascar",
              "Malawi",
              "Mali",
              "Mauritania",
              "Mauritius",
              "Morocco",
              "Mozambique",
              "Namibia",
              "Niger",
              "Nigeria",
              "Rwanda",
              "Sao Tome and Principe",
              "Senegal",
              "Seychelles",
              "Sierra Leone",
              "Somalia",
              "South Africa",
              "South Sudan",
              "Sudan",
              "Tanzania",
              "Togo",
              "Uganda",
              "Zambia",
              "Zimbabwe",
            ],
            America: [
              "Antigua and Barbuda",
              "Argentina",
              "Bahamas",
              "Bolivia",
              "Brazil",
              "Barbados",
              "Belize",
              "Canada",
              "Chile",
              "Colombia",
              "Costa Rica",
              "Cuba",
              "Dominica",
              "Dominican Republic",
              "Ecuador",
              "El Salvador",
              "Grenada",
              "Guatemala",
              "Guyana",
              "Haiti",
              "Honduras",
              "Jamaica",
              "Mexico",
              "Nicaragua",
              "Panama",
              "Paraguay",
              "Peru",
              "Saint Kitts and Nevis",
              "Saint Lucia",
              "Saint Vincent and the Grenadines",
              "Suriname",
              "Trinidad and Tobago",
              "United States",
              "Uruguay",
              "Venezuela",
            ],
            Asia: [
              "Afghanistan",
              "Armenia",
              "Azerbaijan",
              "Bahrain",
              "Bangladesh",
              "Bhutan",
              "Brunei",
              "Cambodia",
              "China",
              "Cyprus",
              "Georgia",
              "India",
              "Indonesia",
              "Iran",
              "Iraq",
              "Israel",
              "Japan",
              "Jordan",
              "Kazakhstan",
              "Kuwait",
              "Kyrgyzstan",
              "Laos",
              "Lebanon",
              "Malaysia",
              "Maldives",
              "Mongolia",
              "Myanmar",
              "Nepal",
              "North Korea",
              "Oman",
              "Pakistan",
              "Palestine",
              "Philippines",
              "Qatar",
              "Saudi Arabia",
              "Singapore",
              "South Korea",
              "Sri Lanka",
              "Syria",
              "Taiwan",
              "Tajikistan",
              "Thailand",
              "Timor-Leste",
              "Turkey",
              "Turkmenistan",
              "United Arab Emirates",
              "Uzbekistan",
              "Vietnam",
              "Yemen",
            ],
            Europe: [
              "Albania",
              "Andorra",
              "Austria",
              "Belarus",
              "Belgium",
              "Bosnia and Herzegovina",
              "Bulgaria",
              "Croatia",
              "Cyprus",
              "Czech Republic",
              "Denmark",
              "Estonia",
              "Finland",
              "France",
              "Germany",
              "Greece",
              "Hungary",
              "Iceland",
              "Ireland",
              "Italy",
              "Kosovo",
              "Latvia",
              "Liechtenstein",
              "Lithuania",
              "Luxembourg",
              "Malta",
              "Moldova",
              "Monaco",
              "Montenegro",
              "Netherlands",
              "North Macedonia",
              "Norway",
              "Poland",
              "Portugal",
              "Romania",
              "Russia",
              "San Marino",
              "Serbia",
              "Slovakia",
              "Slovenia",
              "Spain",
              "Sweden",
              "Switzerland",
              "United Kingdom",
            ],
            Oceania: [
              "Australia",
              "Fiji",
              "Kiribati",
              "Marshall Islands",
              "Micronesia",
              "Nauru",
              "New Zealand",
              "Palau",
              "Papua New Guinea",
              "Samoa",
              "Solomon Islands",
              "Tonga",
              "Tuvalu",
              "Vanuatu",
            ],
          };

          return validCountries[this.continent].includes(value);
        },
        message:
          "Invalid country for the selected continent. Please select a country from your continent.",
      },
    },
  },
  {
    // this second object adds extra properties: `createdAt` and `updatedAt`
    timestamps: true,
  }
);

const User = model("User", userSchema);

module.exports = User;
